# DISCLAIMER: 
# This code was previously part of Joris Heemskerks Bachelors thesis, 
# and is being re-used here. All rights are reserved to Joris Heemskerk, 
# and Technolution BV, Gouda NL. Joris was granted the rights to use and 
# modify this code, at the express notion that a disclaimer was put in.

# Default environment yaml file
# NOTE: See assignment_4/config/config_validation_template.py for the 
# parameter restrictions.

general:
    data_images_path : "assignment_4/data/images/"
    data_annotations_path : "assignment_4/data/annotations/"
    input_image_size: 112
    grid_size: 7
jobs:
    job0:
        train_val_test_split : [0.8, 0.1, 0.1]
        batch_size : 8
        n_features: 256 # hidden dim
        replacement: True # True if model should see the images multiple times
        n_epochs: 100
        learning_rate:  0.00001 # 1e-5
        l1_coefficient: 0.000005 # 5e-6
        lambda_coord: 1
        lambda_noobj: 1
